server:
  port: 8761

#스프링 유레카 서버 구축
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    default-zone: http://localhost:8761/eureka/

spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
